name: "\U0001F41E Bug report"
description: Report an issue with ESLint Plugin De Morgan

title: 'Bug: (fill in)'
labels:
  - bug

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what constitutes an error.
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code example
      description: Please show the code with which you have a bug when using the current plugin.
    validations:
      required: true

  - type: input
    id: eslint-version
    attributes:
      label: ESLint version
      description: Please provide ESLint version.
      placeholder: v1.0.0
    validations:
      required: true

  - type: input
    id: eslint-plugin-de-morgan-version
    attributes:
      label: ESLint Plugin De Morgan version
      description: Please provide ESLint Plugin De Morgan version.
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important to know?

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the docs.
          required: true
        - label: Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-de-morgan/issues) that reports the same bug to avoid creating a duplicate.
          required: true
